import type Phaser from 'phaser';
import { textureKey } from './level/tiled';
import type { BallSize } from './level/types';

/**
 * This game's art, keyed `tb-*` so nothing can collide with the shared set in
 * the page-level texture manager — the rule every game here follows.
 *
 * Pulled in with a Vite glob rather than one import line per file: the art is
 * the Tiled tileset's contents, and that list is already written down in
 * `tools/tilt-ball-tiled/make_tiled.py`. Two hand-maintained copies of it would
 * drift, and the one in the tool is the one Tiled reads.
 *
 * The key for a piece of art is `tb-` + its basename, which is the same
 * derivation the level loader applies to a tileset image path — that is the
 * join between "what Tiled placed" and "what texture to draw".
 */
const artUrls = import.meta.glob('./assets/art/**/*.png', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>;

const thumbUrls = import.meta.glob('./assets/thumbs/*.png', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>;

const stem = (path: string): string => (path.split('/').pop() ?? path).replace(/\.png$/i, '');

/** Queue every piece of this game's art. Idempotent per scene. */
export function loadTiltBallImages(scene: Phaser.Scene): void {
  for (const [path, url] of Object.entries(artUrls)) {
    const key = textureKey(stem(path));
    if (!scene.textures.exists(key)) scene.load.image(key, url);
  }
}

/** Texture key of a level's menu thumbnail. */
export const thumbKey = (levelId: string): string => `tb-thumb-${levelId}`;

/**
 * Queue the baked level thumbnails (`tools/tilt-ball-thumbs`). Only the setup
 * screen needs these, and it is the one screen that must NOT load a level's
 * worth of textures just to show a picture of it.
 */
export function loadLevelThumbs(scene: Phaser.Scene): void {
  for (const [path, url] of Object.entries(thumbUrls)) {
    const key = thumbKey(stem(path));
    if (!scene.textures.exists(key)) scene.load.image(key, url);
  }
}

export function hasThumb(levelId: string): boolean {
  return Object.keys(thumbUrls).some((path) => stem(path) === levelId);
}

/**
 * Ball colours by seat, in the same order as `PLAYER_COLORS` in shared — blue,
 * red, green, yellow-ish — so the ball a player steers matches the swatch they
 * were given in the lobby. Blue and red ship with the pack; green and orange
 * are generated by `tools/recolor/tilt-ball.sh`.
 */
export const BALL_COLOURS = ['blue', 'red', 'green', 'orange'] as const;
export type BallColour = (typeof BALL_COLOURS)[number];

export function ballColour(seat: number): BallColour {
  return BALL_COLOURS[seat % BALL_COLOURS.length]!;
}

export function ballKey(colour: BallColour, size: BallSize): string {
  return textureKey(`ball_${colour}_${size}`);
}

/** The key glyph drawn in the HUD when a level has a lock. */
export const KEY_OUTLINE_KEY = textureKey('key_outline');
