import { registerSounds } from '@kapsel/shared';

import wallUrl from './assets/audio/wall.mp3';
import bounceUrl from './assets/audio/bounce.mp3';
import rotateUrl from './assets/audio/rotate.mp3';
import keyUrl from './assets/audio/key.mp3';
import unlockUrl from './assets/audio/unlock.mp3';
import switchUrl from './assets/audio/switch.mp3';
import laserUrl from './assets/audio/laser.mp3';
import fallUrl from './assets/audio/fall.mp3';
import goalUrl from './assets/audio/goal.mp3';
import respawnUrl from './assets/audio/respawn.mp3';

/**
 * This game's sounds, keyed `tb-*` so nothing can collide with the shared set in
 * the page-level registry — the same rule its textures follow.
 *
 * Registered on import, like `SHARED_SOUNDS` is: it fills a map and does nothing
 * else, so importing this module anywhere in the game is the whole wiring.
 *
 * PLACEHOLDERS, generated by `tools/sfx/generate.py`; `docs/sounds.md` says what
 * each should become. The one to replace first is `tb-wall`, which fires more
 * often than everything else here put together.
 *
 * **There is deliberately no rolling sound.** `tb-roll` was a looping voice per
 * ball whose volume followed its speed, and no synthesised version of it was
 * good enough to keep: filtered noise at four voices reads as a hiss, however
 * its bands are shaped. `docs/sounds.md` keeps the brief and the band shape
 * measured off a real recording, for whoever records the real one — the key goes
 * back in here, and the voices back into `PlayScene`, on the day that lands.
 */
export const TILT_BALL_SOUNDS = {
  /** Ball into a plain wall. Short, dull, quiet: it plays constantly. */
  'tb-wall': wallUrl,
  /** Ball off a bouncy block — deliberately the opposite shape to `tb-wall`. */
  'tb-bounce': bounceUrl,
  /** A block taking its quarter turn, whether or not anyone is near it. */
  'tb-rotate': rotateUrl,
  /** A key taken — the one thing a player does that changes the board for all. */
  'tb-key': keyUrl,
  /** …and its consequence: the walls of that colour going. */
  'tb-unlock': unlockUrl,
  /** A lever thrown — one beam on or off. The same cue in both directions. */
  'tb-switch': switchUrl,
  /** Death by beam. No fall in it. */
  'tb-laser': laserUrl,
  /** Down a death hole: the drop, and the landing. */
  'tb-fall': fallUrl,
  /** Into the goal: the same drop, turning upward instead of landing. */
  'tb-goal': goalUrl,
  /** Versus only — back on the start after a death. */
  'tb-respawn': respawnUrl,
} as const;

registerSounds(TILT_BALL_SOUNDS);
