import { registerSounds } from '@kapsel/shared';

import boostUrl from './assets/audio/boost.mp3';
import crashUrl from './assets/audio/crash.mp3';
import engineUrl from './assets/audio/engine.mp3';
import finishUrl from './assets/audio/finish.mp3';
import freezeUrl from './assets/audio/freeze.mp3';
import lapUrl from './assets/audio/lap.mp3';
import oilUrl from './assets/audio/oil.mp3';
import oilHitUrl from './assets/audio/oil_hit.mp3';
import puTakeUrl from './assets/audio/pu_take.mp3';
import replaceUrl from './assets/audio/replace.mp3';
import rewindUrl from './assets/audio/rewind.mp3';
import skidUrl from './assets/audio/skid.mp3';
import themeUrl from './assets/audio/theme.mp3';

/**
 * This game's own sounds, keyed `rc-*` so nothing can collide with the shared
 * set in the page-level registry — the same rule its textures follow.
 *
 * Registered on import, like `SHARED_SOUNDS` is: it fills a map and does nothing
 * else, so importing this module anywhere in the game is the whole wiring.
 *
 * PLACEHOLDERS, generated by `tools/sfx/generate.py`. `docs/sounds.md` says what
 * each should become.
 */
export const RACING_SOUNDS = {
  /**
   * Held for the whole race, one voice per car, played with `loop: true` and its
   * rate tracking speed. The only looping sound in the app — it is why `sfx`
   * takes a `loop` option at all.
   */
  'rc-engine': engineUrl,
  /** Tyre scrub, faded in and out with how hard a car is cornering. */
  'rc-skid': skidUrl,
  /** Hitting a wall or a solid object hard enough to lose speed over. */
  'rc-crash': crashUrl,
  /** A lap completed. */
  'rc-lap': lapUrl,
  /** Crossing the line for the last time. */
  'rc-finish': finishUrl,
  /** The rewind putting a car back down the racing line. */
  'rc-rewind': rewindUrl,

  // ── Powerups ────────────────────────────────────────────────────────────
  // One-shots, every one of them, and that is deliberate: `sfx` is page-level
  // rather than Phaser's sound manager, so a HELD voice would keep playing
  // straight through a `PauseMenu` pause. Nothing here outlives its cue.
  /** Driving over any pickup. The kind's own cue plays on top of this. */
  'rc-pu-take': puTakeUrl,
  /** Freeze: the rest of the field shut down for three seconds. */
  'rc-freeze': freezeUrl,
  /** Speed: the taker's three seconds of more of everything. */
  'rc-boost': boostUrl,
  /** Oil: slicks going down behind the taker. */
  'rc-oil': oilUrl,
  /**
   * A car spinning out on a slick — the other end of `rc-oil`, and deliberately
   * a different cue: the driver who dropped it and the driver who hits it are
   * having very different afternoons and should not hear the same thing.
   */
  'rc-oil-hit': oilHitUrl,
  /** Replace: the taker and a rival trading places. */
  'rc-replace': replaceUrl,

  /** The race's backing loop, under the engines. */
  'rc-theme': themeUrl,
} as const;

registerSounds(RACING_SOUNDS);
